In [3]:
import pandas as pd
import numpy as np
import pickle
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder,StandardScaler

In [4]:
df = pd.read_csv(r"../data/WA_Fn-UseC_-Telco-Customer-Churn.csv")

In [5]:
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')
df.isnull().sum()

customerID           0
gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

In [6]:
df["TotalCharges"] =  df["TotalCharges"].fillna(0)

In [7]:
df = df.drop(columns="customerID")
df

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.50,No
7039,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.90,No
7040,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,No,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.60,Yes
7042,Male,0,No,No,66,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.50,No

In [8]:
df.isnull().sum()

gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [9]:
#feature engineering

In [10]:
#tenure groups

In [11]:
df['tenure_group'] = pd.cut(df['tenure'],bins=[-1, 12, 24, 48, 72],
    labels=['New', 'Short-term', 'Mid-term', 'Long-term'])

In [12]:
#new customer indicator

In [13]:
df['is_new_customer'] = (df['tenure'] <= 12).astype(int)

In [14]:
df["is_new_customer"].head(10)

0    1
1    0
2    1
3    0
4    1
5    1
6    0
7    1
8    0
9    0
Name: is_new_customer, dtype: int64

In [15]:
#long term customer by checking 4 yeras

In [16]:
df['is_long_term_customer'] = (df['tenure'] > 48).astype(int)
df

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,...,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,tenure_group,is_new_customer,is_long_term_customer
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,...,No,Month-to-month,Yes,Electronic check,29.85,29.85,No,New,1,0
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,...,No,One year,No,Mailed check,56.95,1889.50,No,Mid-term,0,0
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,...,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,New,1,0
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,...,No,One year,No,Bank transfer (automatic),42.30,1840.75,No,Mid-term,0,0
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,...,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,New,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,No,...,Yes,One year,Yes,Mailed check,84.80,1990.50,No,Short-term,0,0
7039,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,Yes,...,Yes,One year,Yes,Credit card (automatic),103.20,7362.90,No,Long-term,0,1
7040,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,No,...,No,Month-to-month,Yes,Electronic check,29.60,346.45,No,New,1,0
7041,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,No,...,No,Month-to-month,Yes,Mailed check,74.40,306.60,Yes,New,1,0
7042,Male,0,No,No,66,Yes,No,Fiber optic,Yes,No,...,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.50,No,Long-term,0,1

In [17]:
service_cols = ['PhoneService','MultipleLines','OnlineSecurity','OnlineBackup','DeviceProtection',
'TechSupport','StreamingTV','StreamingMovies']

In [18]:
df['num_subscribed_services'] = (df[service_cols] == 'Yes').sum(axis=1)

In [19]:
df[['num_subscribed_services'] + service_cols].head(10)

,num_subscribed_services,PhoneService,MultipleLines,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies
0,1,No,No phone service,No,Yes,No,No,No,No
1,3,Yes,No,Yes,No,Yes,No,No,No
2,3,Yes,No,Yes,Yes,No,No,No,No
3,3,No,No phone service,Yes,No,Yes,Yes,No,No
4,1,Yes,No,No,No,No,No,No,No
5,5,Yes,Yes,No,No,Yes,No,Yes,Yes
6,4,Yes,Yes,No,Yes,No,No,Yes,No
7,1,No,No phone service,Yes,No,No,No,No,No
8,6,Yes,Yes,No,No,Yes,Yes,Yes,Yes
9,3,Yes,No,Yes,Yes,No,No,No,No

In [20]:
#optional services

In [21]:
optional_service_cols = ['OnlineSecurity','OnlineBackup','DeviceProtection','TechSupport',
                         'StreamingTV','StreamingMovies']
df['num_optional_services'] = (df[optional_service_cols] == 'Yes').sum(axis=1)

In [22]:
df[['num_optional_services'] + optional_service_cols].head(10)

,num_optional_services,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies
0,1,No,Yes,No,No,No,No
1,2,Yes,No,Yes,No,No,No
2,2,Yes,Yes,No,No,No,No
3,3,Yes,No,Yes,Yes,No,No
4,0,No,No,No,No,No,No
5,3,No,No,Yes,No,Yes,Yes
6,2,No,Yes,No,No,Yes,No
7,1,Yes,No,No,No,No,No
8,4,No,No,Yes,Yes,Yes,Yes
9,2,Yes,Yes,No,No,No,No

In [23]:
#internet service

In [24]:
df['has_internet_service'] = (df['InternetService'] != 'No').astype(int)

In [25]:
df[['InternetService', 'has_internet_service']].head()

  InternetService  has_internet_service
0             DSL                     1
1             DSL                     1
2             DSL                     1
3             DSL                     1
4     Fiber optic                     1

In [26]:
#biling feature

In [27]:
#monthly groups

In [28]:
df['monthly_charge_group'] = pd.cut(df['MonthlyCharges'],bins=[0, 35, 70, df['MonthlyCharges'].max()],
                                    labels=['Low', 'Medium', 'High'])

In [29]:
df[['MonthlyCharges', 'monthly_charge_group']].head(10)

   MonthlyCharges monthly_charge_group
0           29.85                  Low
1           56.95               Medium
2           53.85               Medium
3           42.30               Medium
4           70.70                 High
5           99.65                 High
6           89.10                 High
7           29.75                  Low
8          104.80                 High
9           56.15               Medium

In [30]:
#total groups

In [31]:
df['total_charge_group'] = pd.cut(
    df['TotalCharges'],
    bins=[-1, 1000, 3000, 6000, df['TotalCharges'].max()],
    labels=['Low', 'Medium', 'High', 'Very High'])

In [32]:
df[['TotalCharges', 'total_charge_group']].head(10)

   TotalCharges total_charge_group
0         29.85                Low
1       1889.50             Medium
2        108.15                Low
3       1840.75             Medium
4        151.65                Low
5        820.50                Low
6       1949.40             Medium
7        301.90                Low
8       3046.05               High
9       3487.95               High

In [33]:
#ratio

In [34]:
df['charge_to_tenure_ratio'] = (df['TotalCharges'] / df['tenure'].replace(0, np.nan)).fillna(0)

In [35]:
df[['tenure', 'TotalCharges', 'charge_to_tenure_ratio']].head(10)

   tenure  TotalCharges  charge_to_tenure_ratio
0       1         29.85               29.850000
1      34       1889.50               55.573529
2       2        108.15               54.075000
3      45       1840.75               40.905556
4       2        151.65               75.825000
5       8        820.50              102.562500
6      22       1949.40               88.609091
7      10        301.90               30.190000
8      28       3046.05              108.787500
9      62       3487.95               56.257258

In [36]:
#contract risk

In [37]:
df['contract_risk'] = (df['Contract'] == 'Month-to-month').astype(int)

In [38]:
df[['Contract', 'contract_risk']].head(10)

         Contract  contract_risk
0  Month-to-month              1
1        One year              0
2  Month-to-month              1
3        One year              0
4  Month-to-month              1
5  Month-to-month              1
6  Month-to-month              1
7  Month-to-month              1
8  Month-to-month              1
9        One year              0

In [39]:
df['contract_risk'].value_counts()

contract_risk
1    3875
0    3168
Name: count, dtype: int64

In [40]:
#method risk

In [41]:
df['payment_method_risk'] = (df['PaymentMethod'] == 'Electronic check').astype(int)

In [42]:
df[['PaymentMethod', 'payment_method_risk']].head(10)

               PaymentMethod  payment_method_risk
0           Electronic check                    1
1               Mailed check                    0
2               Mailed check                    0
3  Bank transfer (automatic)                    0
4           Electronic check                    1
5           Electronic check                    1
6    Credit card (automatic)                    0
7               Mailed check                    0
8           Electronic check                    1
9  Bank transfer (automatic)                    0

In [43]:
#service combination risk

In [44]:
df['service_combination_risk'] = ((df['OnlineSecurity'] == 'No') & (df['TechSupport'] == 'No')).astype(int)
df['service_combination_risk'].value_counts()

service_combination_risk
0    4490
1    2553
Name: count, dtype: int64

In [45]:
#high risk

In [46]:
df['high_value_high_risk'] = ((df['TotalCharges'] >= 6000) &(df['contract_risk'] == 1)).astype(int)
df[['TotalCharges', 'Contract', 'contract_risk', 'high_value_high_risk']].head(10)

   TotalCharges        Contract  contract_risk  high_value_high_risk
0         29.85  Month-to-month              1                     0
1       1889.50        One year              0                     0
2        108.15  Month-to-month              1                     0
3       1840.75        One year              0                     0
4        151.65  Month-to-month              1                     0
5        820.50  Month-to-month              1                     0
6       1949.40  Month-to-month              1                     0
7        301.90  Month-to-month              1                     0
8       3046.05  Month-to-month              1                     0
9       3487.95        One year              0                     0

In [47]:
df

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,...,num_subscribed_services,num_optional_services,has_internet_service,monthly_charge_group,total_charge_group,charge_to_tenure_ratio,contract_risk,payment_method_risk,service_combination_risk,high_value_high_risk
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,...,1,1,1,Low,Low,29.850000,1,1,1,0
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,...,3,2,1,Medium,Medium,55.573529,0,0,0,0
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,...,3,2,1,Medium,Low,54.075000,1,0,0,0
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,...,3,3,1,Medium,Medium,40.905556,0,0,0,0
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,...,1,0,1,High,Low,75.825000,1,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,No,...,7,5,1,High,Medium,82.937500,0,0,0,0
7039,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,Yes,...,6,4,1,High,Very High,102.262500,0,0,1,0
7040,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,No,...,1,1,1,Low,Low,31.495455,1,1,0,0
7041,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,No,...,2,0,1,High,Low,76.650000,1,0,1,0
7042,Male,0,No,No,66,Yes,No,Fiber optic,Yes,No,...,6,5,1,High,Very High,103.704545,0,0,0,0

In [48]:
#cat cols adn numeric cols

In [49]:
X = df.drop('Churn', axis=1)
y = df['Churn'].map({'No': 0, 'Yes': 1})

In [50]:
cat_cols = X.select_dtypes(include=['object', 'category']).columns.tolist()
numeric_cols = X.select_dtypes(include=['int64', 'float64']).columns.tolist()

C:\Users\rizwa\AppData\Local\Temp\ipykernel_14568\179740511.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_cols = X.select_dtypes(include=['object', 'category']).columns.tolist()

In [51]:
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.2,random_state=42,stratify=y)

In [52]:
encoder = OneHotEncoder(drop='first',handle_unknown='ignore',sparse_output=False)
X_train_cat = encoder.fit_transform(X_train[cat_cols])
X_test_cat = encoder.transform(X_test[cat_cols])

In [53]:
with open("encoder.pkl", "wb") as file:
    pickle.dump(encoder, file)

In [54]:
scaler = StandardScaler()
X_train_num = scaler.fit_transform(X_train[numeric_cols])
X_test_num = scaler.transform(X_test[numeric_cols])

In [55]:
with open("scaler.pkl", "wb") as file:
    pickle.dump(scaler, file)

In [58]:
print("X_train:", X_train.shape)
print("X_test:", X_test.shape)
print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

X_train: (5634, 48)
X_test: (1409, 48)
y_train: (5634,)
y_test: (1409,)

In [59]:
np.save(r"../data/processed/x_train_fea.npy",X_train)
np.save(r"../data/processed/y_train_fea.npy",y_train)
np.save(r"../data/processed/x_test_fea.npy",X_test)
np.save(r"../data/processed/y_test_fea.npy",y_test)